# Generated by Django 3.0.3 on 2020-05-17 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upoads',
            new_name='Uploads',
        ),
    ]
