# Generated by Django 2.1.15 on 2020-09-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20200517_0701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='file',
        ),
        migrations.AddField(
            model_name='upload',
            name='model',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='upload',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
