# Generated by Django 2.1.15 on 2020-09-25 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20200925_1634'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upload',
            new_name='Model',
        ),
    ]
